### ISSUE TITLE
NotAuthorizedException on SeedRestTest (Windows based execution)

### ISSUE THREAD

**Issue by jazzinjars** [systelab/seed-jee#15]
**Summary**
On a Windows OS, if we execute the maven commad "mvn install", the status of the maven execution is BUILD FAILURE because the SeedRestTest fails due to a NotAuthorizationException.

**Steps to Reproduce**
1. _git clone_ the repository on a Windows machine
2. Launch a _mvn install_
3. The NotAuthorizedException appears

**Expected Result**
Mvn install execution as BUILD SUCCESS

**Actual Result**
Mvn install execution is reported as BUILD FAILURE due to a NotAuthorizationException from SeedRestTest.

**Comment by alfonsserra** [comment]
I have tested the seed in Windows and everything seems to work fine. There is only an issue related to the local maven repository location.

You could have some issues if the local maven repository is in a folder with a name containing white spaces (quite common as the default value is ${user.home}/.m2/repository). In order to avoid this, it is fully recommended that you specify another folder in your maven settings.xml file.     

For example:
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository>/dev/repo</localRepository>
  ...
```
